services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: tsarajoro/piou:8.2
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - '~/.ssh:/home/sail/.ssh'
        networks:
            - app
        depends_on:
            - mariadb.test
            - mailpit.test
    mariadb.test:
        image: 'mariadb:10'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'db:/var/lib/mysql'
        networks:
            - app
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mailpit.test:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - app
    pma.test:
        image: "phpmyadmin"
        restart: always
        ports:
            - "${PMA_PORT:-8888}:80"
        environment:
            PMA_ARBITRARY: 0
            UPLOAD_LIMIT: 1024M
            PMA_PORT: 3306
            PMA_HOST: "mariadb.test"
        networks:
            - app
        volumes:
            - "/tmp:/tmp"
networks:
    app:
        driver: bridge
volumes:
    db:
        driver: local
